
var CONSTANTS = {};
CONSTANTS.ROOT = "/";
CONSTANTS.ROOT_PATH = "/";

//When deploy must be PROD
//CONSTANTS.ENV = "PROD";DEV
CONSTANTS.ENV = "DEV";
////Customer
CONSTANTS.CUSTOMER = "DEV";			//Development Mode

////Local
CONSTANTS.SERVER_CONTEXT = "/MOST_MMC_VMT_Web";
CONSTANTS.SERVER_WS = "/MOST_MMC_VMT_Web";


	
CONSTANTS.AUTH_TYPE="JWT";

CONSTANTS.AUTH_TYPE_JWT = "JWT";	//using JWT
CONSTANTS.AUTH_TYPE_AAD = "AAD";	//using Azure Active Directory

////for Microsoft Azure Active Directory
CONSTANTS.USE_SSO_MS_AZURE = "Y";
CONSTANTS.SSO_MS_AZURE_CONFIG = {
    CLIENT_ID: "4a22c26f-7afa-4726-94a9-3401eda3fef5",
    AUTHORITY: "https://login.microsoftonline.com/adports.ae"
};


//Application Code
//Application Code
CONSTANTS.PROJECT_TITLE = "MOST MMC";
CONSTANTS.SYSTEM_CODE = "MOST";
CONSTANTS.VERSION = '4.041.4041'; // 3 (MOST VERSION) / 010 (SITE: 010 : JPB , 021:ADP/fuzaira, 030: APC/) / 0 (last year)36(weeks)1(deployment time)

CONSTANTS.LOCALES =[
	{"code":"en-US", "codeName":"English"}
];


////Local Development
CONSTANTS.SERVER_DNS = "http://localhost:8080";
////Production for CORS
//CONSTANTS.SERVER_DNS = "http://most.demo.tsb.co.kr";
//CONSTANTS.SERVER_DNS = "http://test-cmost.maersk.net";
//CONSTANTS.SERVER_DNS = "http://192.168.1.123:82/82";
//CONSTANTS.SERVER_DNS = "http://192.168.1.58:8383";
//CONSTANTS.SERVER_DNS = "http://192.168.1.58:8080";

CONSTANTS.MAIN_HEADER_HEIGHT = 32;
CONSTANTS.MENU_EXPANDED_WIDTH = 200;

CONSTANTS.LAIP_PORT_CODE = "VNLAP";
CONSTANTS.LAIP_PORT_NAME = "Long An International Port";
CONSTANTS.LAIP_TMNL_CD = "VNLAP";

CONSTANTS.USER_TYPE_INTERNAL        		= "I";
CONSTANTS.USER_TYPE_EXTERNAL         		= "E";

CONSTANTS.PTNR_TYPE_BROKER                	= "BRK";
CONSTANTS.PTNR_TYPE_SHIPPER_CONSIGNEE     	= "CNS";
CONSTANTS.PTNR_TYPE_CONTAINER_REPAIR_VENDOR = "CRP";
CONSTANTS.PTNR_TYPE_CONTRACTOR            	= "CTT";
CONSTANTS.PTNR_TYPE_FUMIGATOR             	= "FMG";
CONSTANTS.PTNR_TYPE_FORWARDER             	= "FWD";
CONSTANTS.PTNR_TYPE_FREE_ZONE_OPERATOR    	= "FZO";
CONSTANTS.PTNR_TYPE_GOVERMMENT            	= "GVM";
CONSTANTS.PTNR_TYPE_INDIVIDUAL_SHIP_MASTER	= "ISM";
CONSTANTS.PTNR_TYPE_INDIVIDUAL_SHIP_OWNER 	= "ISO";
CONSTANTS.PTNR_TYPE_MARINE_SURVEYOR       	= "MSY";
CONSTANTS.PTNR_TYPE_PORT_OPERATOR         	= "POT";
CONSTANTS.PTNR_TYPE_REPAIR_VENDER         	= "REP";
CONSTANTS.PTNR_TYPE_SHIPPING_AGENCY       	= "SHA";
CONSTANTS.PTNR_TYPE_SHIPPING_LINE         	= "SHP";
CONSTANTS.PTNR_TYPE_STEVEDORING_CO        	= "STV";
CONSTANTS.PTNR_TYPE_TALLY_CO              	= "TLY";
CONSTANTS.PTNR_TYPE_TRUCKER              	= "TRK";

CONSTANTS.PTNR_TYPE_CSC_SUPERVISOR        	= "CSC"; //CSC Supervisor
CONSTANTS.PTNR_TYPE_WS_SUPERVISOR         	= "WS"; //Warehouse Supervisor
CONSTANTS.PTNR_TYPE_PS_SUPERVISOR         	= "PS"; //Port Safety Supervisor
CONSTANTS.PTNR_TYPE_SYSTEM_ADMIN          	= "ADMIN"; // System Admin
CONSTANTS.PTNR_TYPE_BERTH_PLANNER         	= "BP"; // Berth planner

CONSTANTS.SCREEN_MODE_INQUIRY = "inquiry";
CONSTANTS.SCREEN_MODE_CREATE = "create";
CONSTANTS.SCREEN_MODE_UPDATE = "update";
CONSTANTS.SCREEN_MODE_DETAIL = "detail"; //added by Brian (2022/11/30)

CONSTANTS.AUTH_INQUIRY = "inquiry";
CONSTANTS.AUTH_CLEAR = "clear";
CONSTANTS.AUTH_CREATE = "create";
CONSTANTS.AUTH_SAVE = "save";
CONSTANTS.AUTH_DELETE = "delete";
CONSTANTS.AUTH_DOWNLOAD = "download";
CONSTANTS.AUTH_PREVIEW = "preview";
CONSTANTS.AUTH_PRINT = "print";
CONSTANTS.AUTH_HISTORY = "history";

CONSTANTS.INQUIRY_ITEM_ID = "inquiryItemId";
CONSTANTS.CLEAR_ITEM_ID = "clearItemId";
CONSTANTS.CREATE_ITEM_ID = "createItemId";
CONSTANTS.SAVE_ITEM_ID = "saveItemId";
CONSTANTS.DELETE_ITEM_ID = "deleteItemId";
CONSTANTS.DOWNLOAD_ITEM_ID = "downloadItemId";
CONSTANTS.PREVIEW_ITEM_ID = "previewItemId";
CONSTANTS.PRINT_ITEM_ID = "printItemId";
CONSTANTS.HISTORY_ITEM_ID = "historyItemId";

CONSTANTS.CONFIRMED = "Confirmed";
CONSTANTS.APPROVED = "Approved";
CONSTANTS.NOTCONFIRMED = "Not Confirmed";
CONSTANTS.OK = "ok";

CONSTANTS.DEFAULT_BRANCH = "MOST_JPBI";

//added by Brian
CONSTANTS.YES = 'Y';
CONSTANTS.NO = 'N';