Ext.define('MOST.model.map.car.ChartBaseSummaryItem', {
	extend: 'MOST.model.map.foundation.dataitem.DataItem',

	fields: [{
		name:'cargoQtyUnit',
		type:'number'
	},{
		name:'cargoQtyCeu',
		type:'number'
	},{
		name:'durationTotal',
		type:'number'
	},{
		name:'durationNet',
		type:'number'
	},{
		name:'freightAmt',
		type:'number'
	},{
		name:'oprCostAmt',
		type:'number'
	},{
		name:'oprEaringAmt',
		type:'number'
	},{
		name:'dailyCBAmt',
		type:'number'
	},{
		name:'dailyHBAmt',
		type:'number'
	},{
		name:'hireAmt',
		type:'number'
	},{
		name:'offHireAmt',
		type:'number'
	},{
		name:'plAmt',
		type:'number'
	},{
		name:'plRate',
		type:'number'
	
	//Fuel Consumption
	},{
		name:'vesselCode',
		type:'string'
	},{
		name:'speedLdn',
		type:'number'
	},{
		name:'speedEco',
		type:'number'
	},{
		name:'laSeaFo',
		type:'number'
	},{
		name:'laSeaDo',
		type:'number'
	},{
		name:'laPortFo',
		type:'number'
	},{
		name:'laPortDo',
		type:'number'
	},{
		name:'ecSeaFo',
		type:'number'
	},{
		name:'ecSeaDo',
		type:'number'
	},{
		name:'ecPortFo',
		type:'number'
	},{
		name:'ecPortDo',
		type:'number'
	}]
});
