Ext.define('MOST.model.map.admin.Admin', {
	extend: 'MOST.model.map.foundation.dataitem.DataItem',

	fields: [
		{
			name:'physicalDistributionCode',
			type:'string'
		},{
			name:'physicalDistributionName',
			type:'string'
		},{
			name:'physicalDistributionLocation',
			type:'string'
		},{
			name:'physicalDistributionLongitude',
			type:'string'
		},{
			name:'physicalDistributionLatitude',
			type:'string'
		},{
			name:'physicalDistributionCodeCombo',
			type:'string'
		},{
			name:'physicalDistributionNameCombo',
			type:'string'
		},{
			name:'mdtId',
			type:'string'
		},{
			name:'coastMaritimeVesselCode',
			type:'string'
		},{
			name:'serialNo',
			type:'string'
		},{
			name:'mdtInterval',
			type:'string'
		},{
			name:'coastMaritimeRemark',
			type:'string'
		},{
			name:'coastMaritimeVesselName',
			type:'string'
		},{
			name:'coastMaritimeLastRegisterDate',
			type:'string'
		},{
			name:'coastMaritimeRegisterDate',
			type:'string'
		},{
			name:'display',
			type:'string'
		},{
			name:'value',
			type:'string'
		},{
			name:'cdVslknd',
			type:'string'
		},{
			name:'nmVslknd',
			type:'string'
		},{
			name:'gpsServiceRegisterType',
			type:'string'
		},{
			name:'gpsServiceRegisterVesselCode',
			type:'string'
		},{
			name:'gpsServiceRegisterVesselName',
			type:'string'
		},{
			name:'gpsServiceRegisterCallsign',
			type:'string'
		},{
			name:'gpsServiceRegisterConformation',
			type:'string'
		},{
			name:'gpsServiceRegisterSet',
			type:'string'
		},{
			name:'gpsServiceRegisterLastRegisterDate',
			type:'string'
		},{
			name:'cdFeet',
			type:'string'
		},{
			name:'cdFeetStat',
			type:'string'
		},{
			name:'gpsServiceRegistervalue',
			type:'string'
		},{
			name:'gpsServiceRegisterdisplay',
			type:'string'
		}
	]
});