Ext.define('MOST.model.planning.MovementList', {
	extend: 'MOST.model.foundation.dataitem.DataItem',
	requires:[
		'MOST.model.planning.berth.MailItem'
	],
	fields: [{
		name: 'workingStatus',
		type: 'string'
	}, {
		name: 'cgNo',
		type: 'string'
	}, {
		name: 'vslCallId',
		type: 'string'
	}, {
		name: 'jobNo',
		type: 'string'
	}, {
		name: 'jobTpCd',
		type: 'string'
	}, {
		name: 'shftId',
		type: 'string'
	}, {
		name: 'pkgQty',
		type: 'string'
	}, {
		name: 'msrmt',
		type: 'string'
	}, {
		name: 'wgt',
		type: 'string'
	}, {
		name: 'fmPkgQty',
		type: 'string'
	}, {
		name: 'fmMsrmt',
		type: 'string'
	}, {
		name: 'fmWgt',
		type: 'string'
	}, {
		name: 'cntrQty',
		type: 'string'
	}, {
		name: 'fmLocId',
		type: 'string'
	}, {
		name: 'toLocId',
		type: 'string'
	}, {
		name: 'stDt',
		type: 'string',
		
	}, {
		name: 'endDt',
		type: 'string',
	
	}, {
		name: 'statCd',
		type: 'string'
	}, {
		name: 'odrNo',
		type: 'string'
	}, {
		name: 'jobPurpCd',
		type: 'string'
	}, {
		name: 'delvTpCd',
		type: 'string'
	}, {
		name: 'fnlOpeYn',
		type: 'string'
	}, {
		name: 'fnlDelvYn',
		type: 'string'
	}, {
		name: 'opeClassCd',
		type: 'string'
	}, {
		name: 'catgNm',
		type: 'string'
	}, {
		name: 'dmgYn',
		type: 'string'
	}, {
		name: 'stsYn',
		type: 'string'
	}, {
		name: 'shipgAgnt',
		type: 'string'
	}, {
		name: 'fwrAgnt',
		type: 'string'
	}, {
		name: 'shpr',
		type: 'string'
	}, {
		name: 'shprNm',
		type: 'string'
	}, {
		name: 'shprAddr',
		type: 'string'
	}, {
		name: 'cnsne',
		type: 'string'
	}, {
		name: 'cnsneNm',
		type: 'string'
	}, {
		name: 'locId',
		type: 'string'
	}, {
		name: 'locNm',
		type: 'string'
	}, {
		name: 'mvTp',
		type: 'string'
	}, {
		name: 'mvTpNm',
		type: 'string'
	}, {
		name: 'mvDt',
		type: 'string'
	}, {
		name: 'grItem',
		type: 'string'
	}, {
		name: 'blSn',
		type: 'string'
	}, {
		name: 'cargo',
		type: 'string'
	}, {
		name: 'shpCng',
		type: 'string'
	}, {
		name: 'allocateYN',
		type: 'string'
	}, {
		name: 'no',
		type: 'string'
	}, {
		name: 'jobGroup',
		type: 'string'
	}, {
		name: 'shftNm',
		type: 'string'
	}, {
		name: 'shftDt',
		type: 'string'
	}, {
		name: 'locQty',
		type: 'string'
	}, {
		name: 'locWgt',
		type: 'string'
	}, {
		name: 'locMsrmt',
		type: 'string'
	}, {
		name: 'whTpCd',
		type: 'string'
	}, {
		name: 'locArea',
		type: 'string'
	}, {
		name: 'whId',
		type: 'string'
	}, {
		name: 'fmTotalLoc',
		type: 'string'
	}, {
		name: 'toTotalLoc',
		type: 'string'
	}, {
		name: 'fmLoc',
		type: 'string'
	}, {
		name: 'toLoc',
		type: 'string'
	}, {
		name: 'fmDmgLoc',
		type: 'string'
	}, {
		name: 'toDmgLoc',
		type: 'string'
	}, {
		name: 'fmShuLoc',
		type: 'string'
	}, {
		name: 'toShuLoc',
		type: 'string'
	}, {
		name: 'fmDmgRhdlCLoc',
		type: 'string'
	}, {
		name: 'toDmgRhdlCLoc',
		type: 'string'
	}, {
		name: 'fmDmgRhdlRLoc',
		type: 'string'
	}, {
		name: 'toDmgRhdlRLoc',
		type: 'string'
	}, {
		name: 'fmShuRhdlCLoc',
		type: 'string'
	}, {
		name: 'toShuRhdlCLoc',
		type: 'string'
	}, {
		name: 'fmShuRhdlRLoc',
		type: 'string'
	}, {
		name: 'toShuRhdlRLoc',
		type: 'string'
	}, {
		name: 'fmSpSLoc',
		type: 'string'
	}, {
		name: 'toSpSLoc',
		type: 'string'
	}, {
		name: 'fmSpSDmgLoc',
		type: 'string'
	}, {
		name: 'toSpSDmgLoc',
		type: 'string'
	}, {
		name: 'fmSpSShuLoc',
		type: 'string'
	}, {
		name: 'toSpSShuLoc',
		type: 'string'
	}, {
		name: 'fmSpSDmgRhdlCLoc',
		type: 'string'
	}, {
		name: 'toSpSDmgRhdlCLoc',
		type: 'string'
	}, {
		name: 'fmSpSDmgRhdlRLoc',
		type: 'string'
	}, {
		name: 'toSpSDmgRhdlRLoc',
		type: 'string'
	}, {
		name: 'fmSpSShuRhdlCLoc',
		type: 'string'
	}, {
		name: 'toSpSShuRhdlCLoc',
		type: 'string'
	}, {
		name: 'fmSpSShuRhdlRLoc',
		type: 'string'
	}, {
		name: 'toSpSShuRhdlRLoc',
		type: 'string'
	}, {
		name: 'fmSpOLoc',
		type: 'string'
	}, {
		name: 'toSpOLoc',
		type: 'string'
	}, {
		name: 'fmSpODmgLoc',
		type: 'string'
	}, {
		name: 'toSpODmgLoc',
		type: 'string'
	}, {
		name: 'fmSpOShuLoc',
		type: 'string'
	}, {
		name: 'toSpOShuLoc',
		type: 'string'
	}, {
		name: 'fmSpODmgRhdlCLoc',
		type: 'string'
	}, {
		name: 'toSpODmgRhdlCLoc',
		type: 'string'
	}, {
		name: 'fmSpODmgRhdlRLoc',
		type: 'string'
	}, {
		name: 'toSpODmgRhdlRLoc',
		type: 'string'
	}, {
		name: 'fmSpOShuRhdlCLoc',
		type: 'string'
	}, {
		name: 'toSpOShuRhdlCLoc',
		type: 'string'
	}, {
		name: 'fmSpOShuRhdlRLoc',
		type: 'string'
	}, {
		name: 'toSpOShuRhdlRLoc',
		type: 'string'
	}, {
		name: 'rhdlMode',
		type: 'string'
	}, {
		name: 'shuYn',
		type: 'string'
	}, {
		name: 'jobCoCd',
		type: 'string'
	}, {
		name: 'spCaCoCd',
		type: 'string'
	}]
   
});