Ext.define('MOST.model.controller.ContainerProcessItem', {
    extend: 'MOST.model.foundation.dataitem.DataItem',
    fields: [
		{
			name:'vslCallId',
			type:'string'
		},
		{
			name:'seq',
			type:'string'
        },
        {
			name:'stDt',
			type:'string'
        },
        {
			name:'endDt',
			type:'string'
        },
        {
			name:'shftId',
			type:'string'
        },
        {
			name:'shftNm',
			type:'string'
        },
        {
			name:'hatchNo',
			type:'string'
        },
        {
			name:'eqNo',
			type:'string'
        },
        {
			name:'eqNm',
			type:'string'
        },
        {
			name:'totalHrs',
			type:'string'
        },
        {
			name:'userId',
			type:'string'
        },
        {
			name:'no',
			type:'string'
        },
        {
			name:'l20',
			type:'string'
        },
        {
			name:'l40',
			type:'string'
        },
        {
			name:'d20',
			type:'string'
        },
        {
			name:'d40',
			type:'string'
        },
        {
			name:'workYmd',
			type:'string'
		},
    ]
})