Ext.define('MOST.model.operation.SearchServiceOrderParm', {
    extend: 'MOST.model.foundation.parm.BizParm',
    fields: [
    	{
    		name:'seq',
    		type:'string'
    	},
    	{
    		name:'odrNo',
    		type:'string'
    	},
    	{
    		name:'category1',
    		type:'string'
    	},
    	{
    		name:'category2',
    		type:'string'
    	},
    	{
    		name:'category3',
    		type:'string'
    	},
    	{
    		name:'category1Nm',
    		type:'string'
    	},
    	{
    		name:'category2Nm',
    		type:'string'
    	},
    	{
    		name:'category3Nm',
    		type:'string'
    	},
    	{
    		name:'vslCallId',
    		type:'string'
    	},
    	{
    		name:'svcDtFm',
    		type:'string'
    	},
    	{
    		name:'svcDtTo',
    		type:'string'
    	},
    	{
    		name:'shftId',
    		type:'string'
    	},
    	{
    		name:'statCd',
    		type:'string'
    	},
    	{
    		name:'userRole',
    		type:'string'
    	},
    	{
    		name:'searchType',
    		type:'string'
    	},
    	{
    		name:'subSearchType',
    		type:'string'
    	},
    	{
    		name:'alertYn',
    		type:'string'
    	}
    ]
});

