Ext.define('MOST.model.planning.berth.BerthApproval', {
	extend: 'MOST.model.foundation.dataitem.DataItem',
	requires:[
		'MOST.model.planning.berth.MailItem'
	],
	fields: [{
		name: 'vslNm',
		type: 'string'
	}, {
		name: 'jpvcNo',
		type: 'string'
	}, {
		name: 'eta',
		type: 'string'
	}, {
		name: 'clrYymm',
		type: 'string'
	}, {
		name: 'summitStat',
		type: 'string'
	}, {
		name: 'summitStatName',
		type: 'string'
	}, {
		name: 'status',
		type: 'string'
	}, {
		name: 'loa',
		type: 'float'
	}, {
		name: 'vslCd',
		type: 'string'
	}, {
		name: 'vslFlagCd',
		type: 'string'
	}, {
		name: 'cntryCd',
		type: 'string'
	}, {
		name: 'vslTp',
		type: 'string'
	}, {
		name: 'nrt',
		type: 'float'
	}, {
		name: 'grt',
		type: 'float'
	}, {
		name: 'saCorpId',
		type: 'string'
	}, {
		name: 'sumitDt',
		type: 'date',
		dateFormat: 'time'
	}, {
		name: 'insDtm',
		type: 'date',
		dateFormat: 'time'
	}, {
		name: 'berthLoc',
		type: 'string'
	}, {
		name: 'arrvSaId',
		type: 'string'
	}, {
		name: 'mptsStat',
		type: 'string'
	}, {
		name: 'mptsStatNm',
		type: 'string'
	}, {
		name: 'callYear',
		type: 'string'
	}, {
		name: 'callSeq',
		type: 'string'
	}, {
		name: 'balance',
		type: 'string'
	}, {
		name: 'mt',
		type: 'string'
	}, {
		name: 'fileYn',
		type: 'string'
	}, {
		name: 'consignee',
		type: 'string'
	}, {
		name: 'consignor',
		type: 'string'
	}, {
		name: 'operationType',
		type: 'string'
	}, {
		name: 'vslTpNm',
		type: 'string'
	}, {
		name: 'berthTp',
		type: 'string'
	}, {
		name: 'berthPlanYn',
		type: 'string'
	}, {
		name: 'cargoTp',
		type: 'string'
	}, {
		name: 'vslColor',
		type: 'string'
	}, {
		name: 'mptsStatDt',
		type: 'string'
	}, {
		name: 'userId',
		type: 'string'
	}, {
		name: 'berthAprvUserId',
		type: 'string'
	}, {
		name: 'mailItem',
		mapping: 'MOST.model.planning.berth.MailItem'
	}],
    associations: [{
		type: 'hasMany',
		name: 'mailItemMap',
		model: 'MOST.model.planning.berth.MailItem'
	}]  
});