Ext.define('MOST.model.planning.berth.VesselAgency', {
	extend: 'MOST.model.foundation.dataitem.DataItem',
	
	fields: [{
		name: 'engSnm',
		type: 'string'
	}, {
		name: 'agencyCode',
		type: 'string'
	}, {
		name: 'companyStatus',
		type: 'string'
	}, {
		name: 'contactPerson',
		type: 'string'
	}, {
		name: 'ptnrType',
		type: 'string'
	}, {
		name: 'addr',
		type: 'string'
	}, {
		name: 'textNo',
		type: 'string'
	}, {
		name: 'faxNo',
		type: 'string'
	}, {
		name: 'homepage',
		type: 'string'
	}, {
		name: 'email',
		type: 'string'
	}, {
		name: 'licNo',
		type: 'string'
	}, {
		name: 'paymentType',
		type: 'string'
	}, {
		name: 'creditLimit',
		type: 'string'
	}, {
		name: 'outstanding',
		type: 'string'
	}, {
		name: 'balance',
		type: 'string'
	}, {
		name: 'accNo',
		type: 'string'
	}, {
		name: 'remark',
		type: 'string'
	}, {
		name: 'vslNm',
		type: 'string'
	}, {
		name: 'hndTp',
		type: 'string'
	}, {
		name: 'jpvcNo',
		type: 'string'
	}, {
		name: 'loa',
		type: 'string'
	}, {
		name: 'cgTp',
		type: 'string'
	}, {
		name: 'cgNm',
		type: 'string'
	}, {
		name: 'etw',
		type: 'string'
	}, {
		name: 'eta',
		type: 'string'
	}, {
		name: 'etc',
		type: 'string'
	}, {
		name: 'etd',
		type: 'string'
	}, {
		name: 'tonnage',
		type: 'string'
	}, {
		name: 'opeTp',
		type: 'string'
	}, {
		name: 'loadCargo',
		type: 'string'
	}, {
		name: 'dischargeCargo',
		type: 'string'
	}, {
		name: 'billTpCd',
		type: 'string'
	}]
});