Ext.define('MOST.model.map.bulk.PositionStatistics', {
	extend: 'MOST.model.map.foundation.dataitem.DataItem',

	fields: [{
		name: 'className',
		type: 'string'
	}, {
		name: 'duration01',
		type: 'string'
	}, {
		name: 'duration02',
		type: 'string'
	}, {
		name: 'duration03',
		type: 'string'
	}, {
		name: 'duration04',
		type: 'string'
	}, {
		name: 'duration05',
		type: 'string'
	}, {
		name: 'duration06',
		type: 'string'
	}, {
		name: 'duration07',
		type: 'string'
	}, {
		name: 'duration08',
		type: 'string'
	}, {
		name: 'duration09',
		type: 'string'
	}, {
		name: 'duration10',
		type: 'string'
	}, {
		name: 'duration11',
		type: 'string'
	}, {
		name: 'duration12',
		type: 'string'
	}, {
		name: 'duration13',
		type: 'string'
	}, {
		name: 'duration14',
		type: 'string'
	}, {
		name: 'duration15',
		type: 'string'
	}, {
		name: 'totalDuration',
		type: 'string'
	}, {
		name: 'duration',
		type: 'string'
	}, {
		name: 'todate',
		type: 'string'
	}, {
		name: 'tonnageValue',
		type: 'string'
	}, {
		name: 'cargoValue',
		type: 'string'
	}, {
		name: 'diffValue',
		type: 'string'
	}]
});
