Ext.define('MOST.model.configuration.ServiceOrderSetting', {
    extend: 'MOST.model.foundation.dataitem.DataItem',
    fields: [{
        name: 'category1',
        type: 'string'
    }, {
        name: 'category1Nm',
        type: 'string'
    }, {
        name: 'seq',
        type: 'number'
    }, {
        name: 'category2',
        type: 'string'
    }, {
        name: 'category2Nm',
        type: 'string'
    }, {
        name: 'category3',
        type: 'string'
    }, {
        name: 'category3Nm',
        type: 'string'
    }, {
        name: 'svcDtFmt',
        type: 'string'
    }, {
        name: 'svcDtTp',
        type: 'string'
    }, {
        name: 'dt1Chk',
        type: 'string'
    }, {
        name: 'dt1Tit',
        type: 'string'
    }, {
        name: 'dt1Fmt',
        type: 'string'
    }, {
        name: 'dt1Tp',
        type: 'string'
    }, {
        name: 'dt2Chk',
        type: 'string'
    }, {
        name: 'dt2Tit',
        type: 'string'
    }, {
        name: 'dt2Fmt',
        type: 'string'
    }, {
        name: 'dt2Tp',
        type: 'string'
    }, {
        name: 'shftChk',
        type: 'string'
    }, {
        name: 'unitTit',
        type: 'string'
    }, {
        name: 'unitUom',
        type: 'string'
    }, {
        name: 'unitUomNm',
        type: 'string'
    }, {
        name: 'unitDec',
        type: 'int',
        defaultValue: 0
    }, {
        name: 'unit1Chk',
        type: 'string'
    }, {
        name: 'unit1Tit',
        type: 'string'
    }, {
        name: 'unit1Uom',
        type: 'string'
    }, {
        name: 'unit1UomNm',
        type: 'string'
    }, {
        name: 'unit1Dec',
        type: 'int',
        defaultValue: 0
    }, {
        name: 'unit2Chk',
        type: 'string'
    }, {
        name: 'unit2Tit',
        type: 'string'
    }, {
        name: 'unit2Uom',
        type: 'string'
    }, {
        name: 'unit2UomNm',
        type: 'string'
    }, {
        name: 'unit2Dec',
        type: 'int',
        defaultValue: 0
    }, {
        name: 'payTpCd',
        type: 'string'
    }, {
        name: 'payTpNm',
        type: 'string'
    }, {
        name: 'prcTpCd',
        type: 'string'
    }, {
        name: 'prcTpNm',
        type: 'string'
    }, {
        name: 'prcTpDesc',
        type: 'string'
    }, {
        name: 'locChk',
        type: 'string'
    }, {
        name: 'rmkChk',
        type: 'string'
    }, {
        name: 'updDt',
        type: 'string'
    }, {
        name: 'updUserId',
        type: 'string'
    }, {
        name: 'version',
        type: 'string'
    }, {
        name: 'cmdtyChk',
        type: 'string'
    }, {
        name: 'documentChk',
        type: 'string'
    }, {
        name: 'unitChk',
        type: 'string'
    }, {
        name: 'documentTp',
        type: 'string'
    },{
        name: 'documentNm',
        type: 'string'
    }]
});
